<a href="https://colab.research.google.com/github/NishmthaM/numpy_basics/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
##rand() function

import numpy as np
rand= np.random.rand(4)
print(rand)

print()

rand1= np.random.rand(2,4)  ## 2 rows and 4 columns
print(rand1)



[0.90451471 0.62179492 0.29890727 0.48924167]

[[0.33986839 0.02058418 0.33146444 0.98436032]
 [0.57994953 0.43960952 0.71578064 0.80238439]]


In [ ]:
import numpy as np
rand= np.random.rand(4)  ## same values but different numbers
print(rand)

[0.69412549 0.51104502 0.92451985 0.01447116]


In [ ]:
## randn() : Generates both p+ve and n-ve values

randn=np.random.randn(4)
print(randn)

[ 0.15583698  1.57543288  0.44209981 -0.61782205]


In [ ]:
## ranf() : 1 is not included [0.0, 1.0)
import numpy as np

var= np.random.ranf(5)
print(var)

[0.43961648 0.97965007 0.1681216  0.51355739 0.96730929]


In [ ]:
## randint() : give the values b/w the two min max values number
#randint(min,max,total_number)
#random integers

var1= np.random.randint(2,6,3)
print(var1)



[5 3 5]


In [ ]:
## data types of numpy array

import numpy as np

var = np.array([1,2,3,4,5])
print("DataType :",var.dtype)

DataType : int64


In [ ]:
import numpy as np

var = np.array([1.96,2.86,3.72,4.64,5.23])
print("DataType :",var.dtype)

DataType : float64


In [ ]:
import numpy as np

var = np.array([1,2,3,4,5,1.26,20.78,"A","C"])
print("DataType :",var.dtype)

DataType : <U32


In [ ]:
## converting one data type into another data type

import numpy as np

x= np.array([1,2,3])
print("Data Type:",x.dtype)

x=np.array([1,2,3],dtype=np.int8)
print("Data type:",x.dtype)


Data Type: int64
Data type: int8


In [ ]:
x1= np.array([1,2],dtype="f")
print(x1.dtype)

x2= np.array([1,2],dtype="c")
print(x2.dtype)

float32
|S1


In [ ]:
#Airthemetic operations in numpy in 1D array

#addition

import numpy as np

a=np.array([1,2,3,4])

varadd= a+3

print(varadd)

[4 5 6 7]


In [ ]:
a1=np.array([1,2,3,4])
a2=np.array([1,2,3,4])

varadd= a1+a2

print(varadd)

[2 4 6 8]


In [ ]:
#subtraction

b1=np.array([1,2,3,4])
b2=np.array([2,6,7,8])

varsub= b1-2

varsub2=b2-b1

print(varsub)
print(varsub2)



[-1  0  1  2]
[1 4 4 4]


In [ ]:
#multiplication

c1=np.array([2,5,3])
c2=np.array([5,6,7])

varmulti1=c1*5
varmulti2=c2*5

varmulti3=c1*c2

print(varmulti1)
print(varmulti2)
print(varmulti3)

[10 25 15]
[25 30 35]
[10 30 21]


In [ ]:
#Division

d1=np.array([1,2,3,4])
d2=np.array([2,3,6,7])

vardiv1=d1/2
vardiv2=d2/2

vardiv3=d2/d1

print(vardiv1)
print(vardiv2)
print(vardiv3)

[0.5 1.  1.5 2. ]
[1.  1.5 3.  3.5]
[2.   1.5  2.   1.75]


In [ ]:
#Modulus

e1=np.array([1,2.3,4])
e2=np.array([3,4,7,8,])

varmod1=e1%2
varmod2=e2%2

print(varmod1)
print(varmod2)

[1.  0.3 0. ]
[1 0 1 0]


In [ ]:
##using built in functions

##Addition

a1=np.array([1,2,3,4])
a2=np.array([1,2,3,4])

varadd= np.add(a1,a2)

print(varadd)

[2 4 6 8]


In [ ]:
#subtraction

b1=np.array([2,2,3,4])
b2=np.array([2,6,7,8])

varsub=np.subtract(b2,b1)

print(varsub)

print()

#multiplication

c1=np.array([2,5,3])
c2=np.array([5,6,7])

varmulti=np.multiply(c1,c2)

print(varmulti)

print()

#Division

d1=np.array([1,2,3])
d2=np.array([2,3,6])

vardiv=np.divide(d1,d2)

print(vardiv)

print()

#Modulus

e1=np.array([1,2.3,4])

varmod=np.mod(e1,2)

print(varmod)

print()

##power

a1=np.array([12,3,4])

varpow=np.power(a1,3)

print(varpow)


[0 4 4 4]

[10 30 21]

[0.5        0.66666667 0.5       ]

[1.  0.3 0. ]

[1728   27   64]


In [ ]:
#Modulus

e1=np.array([1,2.3,4])

varmod=np.mod(e1,2)

print(varmod)

[1.  0.3 0. ]


In [ ]:
#Airthemetic operations in numpy in 2D array

#addition

import numpy as np

a=np.array([[1,2,3,4],[2,3,4,5]])
b=np.array([[2,5,4,8],[8,4,5,6]])

varadd= np.add(a,b)
print("2D addition")

print()

print(varadd)

print()

## 2D subtraction

c=np.array([[1,2,3,4],[2,3,4,5]])
d=np.array([[2,5,4,8],[8,4,5,6]])

varsub=np.subtract(d,c)

print("2D subtraction")
print()
print(varsub)

print()

##2D Multiplication

c1=np.array([[1,2,3,4],[2,3,4,5]])
d1=np.array([[2,5,4,8],[8,4,5,6]])

varmulti=np.multiply(c1,d1)

print("2D Multiplication")
print()
print(varmulti)

print()

##2D division

c2=np.array([[1,2,3,4],[2,3,4,5]])
d2=np.array([[2,5,4,8],[8,4,5,6]])

vardiv=np.divide(d2,c2)

print("2D division")
print()
print(vardiv)
print()

##2D Modulus

e=np.array([[2,3,4,5],[5,4,6,5]])

varmod=np.mod(e,5)

print("2D Modulus")
print()
print(varmod)
print()



2D addition

[[ 3  7  7 12]
 [10  7  9 11]]

2D subtraction

[[1 3 1 4]
 [6 1 1 1]]

2D Multiplication

[[ 2 10 12 32]
 [16 12 20 30]]

2D division

[[2.         2.5        1.33333333 2.        ]
 [4.         1.33333333 1.25       1.2       ]]

2D Modulus

[[2 3 4 0]
 [0 4 1 0]]



In [ ]:
#Airthemetic Functions
#1D array

import numpy as np

a=np.array([2,3,4,7,9,4,6,29,45,23,])

print("Minimum value =",np.min(a))
print("Maximum value =",np.max(a))
print("Position of min =",np.argmin(a))
print("Position of max =",np.argmax(a))
print("square root =",np.sqrt(a))

print()

##2D array

b=np.array([[2,6,4,],[9,5,4]])

print("Minimum value =",np.min(b,axis=0)) #min value in columns
print("Minimum value =",np.min(b,axis=1)) #min value in rows
print("Maximum value =",np.max(b,axis=0)) #max value in columns
print("Maximum value =",np.max(b,axis=1)) #max value in columns
print("Position of min =",np.argmin(a))
print("Position of max =",np.argmax(a))
print("Square root =",np.sqrt(b))

Minimum value = 2
Maximum value = 45
Position of min = 0
Position of max = 8
square root = [1.41421356 1.73205081 2.         2.64575131 3.         2.
 2.44948974 5.38516481 6.70820393 4.79583152]

Minimum value = [2 5 4]
Minimum value = [2 4]
Maximum value = [9 6 4]
Maximum value = [6 9]
Position of min = 0
Position of max = 8
Square root = [[1.41421356 2.44948974 2.        ]
 [3.         2.23606798 2.        ]]


In [ ]:
c= np.array([2,4,6])

print(np.sin(c))
print(np.cos(c))
print(np.tan(c))
print(np.cumsum(c))

[ 0.90929743 -0.7568025  -0.2794155 ]
[-0.41614684 -0.65364362  0.96017029]
[-2.18503986  1.15782128 -0.29100619]
[ 2  6 12]


In [ ]:
#to find shape

import numpy as np

a=np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(a)
print(a.ndim)

(2, 3)
[[1 2 3]
 [4 5 6]]
2


In [ ]:
#for multidimensional array

b=np.array([2,5,8],ndmin=5)

print(b.shape)
print()
print(b)
print()
print(b.ndim)

(1, 1, 1, 1, 3)

[[[[[2 5 8]]]]]

5


In [ ]:
##Reshape the array

import numpy as np

a= np.array([1,2,3,4,5,6,7,8])
b=(a.reshape(4,2))
print(b)
print(b.ndim)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
2


In [ ]:
a1= np.array([2,5,7,8,9,45,15,6])
print(a)
print()

b1=a1.reshape(2,2)
print(b1)
print(b1.ndim)

[1 2 3 4 5 6 7 8]

[[ 2  5]
 [ 7  8]
 [ 9 45]
 [15  6]]
2


In [ ]:
import numpy as np

a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

c=np.add(a,b)
print(c)

[ 6  8 10 12]


In [ ]:
# brodcasting numpy arrays
# When we perform airthmetic operations
#import numpy as np

#a1=np.array([1,2,3,4])
#b1=np.array([5,6,7])    #elements are not same so the bordcasting error will come

#c1= np.add(a1,b1)
#print(c1)


#rules
# Same diamension
# Missing dimensions are treated as
# Compare shapes from the right

In [ ]:
# different diamension

import numpy as np

a= np.array([1,2,3])  # 1 x 3
print(a.shape)
print()
print(a)

print()

b=np.array([[1],[2],[3]])  # 3 x 1
print(b.shape)
print()
print(b)

print()

c=np.add(a,b)
print(c)

(3,)

[1 2 3]

(3, 1)

[[1]
 [2]
 [3]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [ ]:
x= np.array([[1],[2]])  # shape 2 x 1
print("2 x 1 array =>",x.shape)
print()
print(x)

y= np.array([[1,2,3],[2,3,4]])
print()
print("2 x 3 array =>",y.shape)
print()
print(y)

2 x 1 array => (2, 1)

[[1]
 [2]]

2 x 3 array => (2, 3)

[[1 2 3]
 [2 3 4]]


In [ ]:
# indexing and slicing in numpy array

# for 1D

import numpy as np

a= np.array([1,2,3,4])
#indexing    0 1 2 3
#-ve index  -4-3-2-1
print(a[2])  # to get value of 2 index
print(a[-3]) # to get -ve index

3
2


In [ ]:
# for 2D array

import numpy as np
#        row    0          1
a=np.array([[1,2,3,4],[7,8,9,5]])
#   column   0 1 2 3   0 1 2 3

print(a)
print()
print("Diamension =",a.ndim)
print("Value at  0th row and 3rd column index = ",a[0,3])

[[1 2 3 4]
 [7 8 9 5]]

Diamension = 2
Value at  0th row and 3rd column index =  4


In [ ]:
# 3D array

import numpy as np

a= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a)
print()
print("Diamension =",a.ndim)
print()
print("values of 0th row (1st row 0th column) in index ",a[0,1,0])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Diamension = 3

values of 0th row (1st row 0th column) in index  4


In [ ]:
import numpy as np

a= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a)
print()
print("Diamension =",a.ndim)
print()
print("values of 1th row (0st row 2th column) in index ",a[1,0,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Diamension = 3

values of 1th row (0st row 2th column) in index  9


In [ ]:
# Slicing

# for 1D array

import numpy as np

a=np.array([10,20,30,40,50,60])
#           0  1  2  3  4  5

print(a)
print()

print("value from 2 to 5",a[1:5])
print("value from 3 to end",a[2:])
print("value from 2 to 5",a[:4])
print("jumping numbers",a[0:5:2]) # need 10 to 50 number by increasing 2

[10 20 30 40 50 60]

value from 2 to 5 [20 30 40 50]
value from 3 to end [30 40 50 60]
value from 2 to 5 [10 20 30 40]
jumping numbers [10 30 50]


In [ ]:
# Slicing in 2D array

import numpy as np

#             0  1  2  3  4    0  1  2  3  4
a=np.array([[10,20,30,40,50],[60,70,80,90,100]])
#                 0th row         1st row
print(a)
print()

print("value from 0th row from 20 to 50",a[0,1:])
print("value from 1st row from 70 to 100",a[1,1:])
print("value from 0th row from 20 to 40",a[0, 1:4])
print("value from 1st row from 60 to 80",a[1, 0:3])

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]

value from 0th row from 20 to 50 [20 30 40 50]
value from 1st row from 70 to 100 [ 70  80  90 100]
value from 0th row from 20 to 40 [20 30 40]
value from 1st row from 60 to 80 [60 70 80]


In [1]:
# Iterating numpy arrays
# uses for loop for iteration

import numpy as np

a=np.array([9,8,7,6,5,4,3,2,1])
print(a)
print()
for i in a:
  print(i)

[9 8 7 6 5 4 3 2 1]

9
8
7
6
5
4
3
2
1


In [6]:
# Iterating 2D array

b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)
print()

for j in b:
  print(j)
print()

for k in b:
  for l in k:  # for 2D use for loop 2 times
    print(l)


[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4]
[5 6 7 8]

1
2
3
4
5
6
7
8


In [10]:
# Iterating 3D array

import numpy as np

a= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a)
print(a.ndim)
print()


#use 3 for loops for 3D array iteration
for i in a:
  for j in i:
    for k in j:
      print(k)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3

1
2
3
4
5
6
7
8


In [13]:
# instead of using for loop again and again we can use "ndtier() function"

import numpy as np

a= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a)
print()

for i in np.nditer(a): # np.nditer(var_naame)
  print(i)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

1
2
3
4
5
6
7
8


In [14]:
# to get index of the values
# use ndenumerate() function

import numpy as np

a= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a)
print()

for i,d in np.ndenumerate(a):  # gives both index value and data value
  print(i,d)                   # d is data value





[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8
