<a href="https://colab.research.google.com/github/NishmthaM/numpy_basics/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
##rand() function

import numpy as np
rand= np.random.rand(4)
print(rand)

print()

rand1= np.random.rand(2,4)  ## 2 rows and 4 columns
print(rand1)



[0.90451471 0.62179492 0.29890727 0.48924167]

[[0.33986839 0.02058418 0.33146444 0.98436032]
 [0.57994953 0.43960952 0.71578064 0.80238439]]


In [ ]:
import numpy as np
rand= np.random.rand(4)  ## same values but different numbers
print(rand)

[0.69412549 0.51104502 0.92451985 0.01447116]


In [ ]:
## randn() : Generates both p+ve and n-ve values

randn=np.random.randn(4)
print(randn)

[ 0.15583698  1.57543288  0.44209981 -0.61782205]


In [ ]:
## ranf() : 1 is not included [0.1, 1.0)

var= np.random.ranf(5)
print(var)

[0.90419933 0.27981549 0.76570193 0.71868427 0.14571367]


In [ ]:
## randint() : give the values b/w the two min max values number
#randint(min,max,total_number)

var1= np.random.randint(2,6,3)
print(var1)

[5 3 5]


In [ ]:
## data types of numpy array

import numpy as np

var = np.array([1,2,3,4,5])
print("DataType :",var.dtype)

DataType : int64


In [ ]:
import numpy as np

var = np.array([1.96,2.86,3.72,4.64,5.23])
print("DataType :",var.dtype)

DataType : float64


In [ ]:
import numpy as np

var = np.array([1,2,3,4,5,1.26,20.78,"A","C"])
print("DataType :",var.dtype)

DataType : <U32


In [ ]:
## converting one data type into another data type

import numpy as np

x= np.array([1,2,3])
print("Data Type:",x.dtype)

x=np.array([1,2,3],dtype=np.int8)
print("Data type:",x.dtype)


Data Type: int64
Data type: int8


In [ ]:
x1= np.array([1,2],dtype="f")
print(x1.dtype)

x2= np.array([1,2],dtype="c")
print(x2.dtype)

float32
|S1


In [ ]:
#Airthemetic operations in numpy

import numpy as np

a=np.array([1,2,3,4])

varadd= a+3

print(varadd)

[4 5 6 7]


In [ ]:
a1=np.array([1,2,3,4])
a2=np.array([1,2,3,4])

varadd= a1+a2

print(varadd)

[2 4 6 8]
