<a href="https://colab.research.google.com/github/NishmthaM/numpy_basics/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
##rand() function

import numpy as np
rand= np.random.rand(4)
print(rand)

print()

rand1= np.random.rand(2,4)  ## 2 rows and 4 columns
print(rand1)



[0.90451471 0.62179492 0.29890727 0.48924167]

[[0.33986839 0.02058418 0.33146444 0.98436032]
 [0.57994953 0.43960952 0.71578064 0.80238439]]


In [ ]:
import numpy as np
rand= np.random.rand(4)  ## same values but different numbers
print(rand)

[0.69412549 0.51104502 0.92451985 0.01447116]


In [ ]:
## randn() : Generates both p+ve and n-ve values

randn=np.random.randn(4)
print(randn)

[ 0.15583698  1.57543288  0.44209981 -0.61782205]


In [ ]:
## ranf() : 1 is not included [0.1, 1.0)

var= np.random.ranf(5)
print(var)

[0.90419933 0.27981549 0.76570193 0.71868427 0.14571367]


In [ ]:
## randint() : give the values b/w the two min max values number
#randint(min,max,total_number)

var1= np.random.randint(2,6,3)
print(var1)

[5 3 5]


In [ ]:
## data types of numpy array

import numpy as np

var = np.array([1,2,3,4,5])
print("DataType :",var.dtype)

DataType : int64


In [ ]:
import numpy as np

var = np.array([1.96,2.86,3.72,4.64,5.23])
print("DataType :",var.dtype)

DataType : float64


In [ ]:
import numpy as np

var = np.array([1,2,3,4,5,1.26,20.78,"A","C"])
print("DataType :",var.dtype)

DataType : <U32


In [ ]:
## converting one data type into another data type

import numpy as np

x= np.array([1,2,3])
print("Data Type:",x.dtype)

x=np.array([1,2,3],dtype=np.int8)
print("Data type:",x.dtype)


Data Type: int64
Data type: int8


In [ ]:
x1= np.array([1,2],dtype="f")
print(x1.dtype)

x2= np.array([1,2],dtype="c")
print(x2.dtype)

float32
|S1


In [ ]:
#Airthemetic operations in numpy in 1D array

#addition

import numpy as np

a=np.array([1,2,3,4])

varadd= a+3

print(varadd)

[4 5 6 7]


In [ ]:
a1=np.array([1,2,3,4])
a2=np.array([1,2,3,4])

varadd= a1+a2

print(varadd)

[2 4 6 8]


In [12]:
#subtraction

b1=np.array([1,2,3,4])
b2=np.array([2,6,7,8])

varsub= b1-2

varsub2=b2-b1

print(varsub)
print(varsub2)



[-1  0  1  2]
[1 4 4 4]


In [13]:
#multiplication

c1=np.array([2,5,3])
c2=np.array([5,6,7])

varmulti1=c1*5
varmulti2=c2*5

varmulti3=c1*c2

print(varmulti1)
print(varmulti2)
print(varmulti3)

[10 25 15]
[25 30 35]
[10 30 21]


In [14]:
#Division

d1=np.array([1,2,3,4])
d2=np.array([2,3,6,7])

vardiv1=d1/2
vardiv2=d2/2

vardiv3=d2/d1

print(vardiv1)
print(vardiv2)
print(vardiv3)

[0.5 1.  1.5 2. ]
[1.  1.5 3.  3.5]
[2.   1.5  2.   1.75]


In [16]:
#Modulus

e1=np.array([1,2.3,4])
e2=np.array([3,4,7,8,])

varmod1=e1%2
varmod2=e2%2

print(varmod1)
print(varmod2)

[1.  0.3 0. ]
[1 0 1 0]


In [17]:
##using built in functions

##Addition

a1=np.array([1,2,3,4])
a2=np.array([1,2,3,4])

varadd= np.add(a1,a2)

print(varadd)

[2 4 6 8]


In [50]:
#subtraction

b1=np.array([2,2,3,4])
b2=np.array([2,6,7,8])

varsub=np.subtract(b2,b1)

print(varsub)

print()

#multiplication

c1=np.array([2,5,3])
c2=np.array([5,6,7])

varmulti=np.multiply(c1,c2)

print(varmulti)

print()

#Division

d1=np.array([1,2,3])
d2=np.array([2,3,6])

vardiv=np.divide(d1,d2)

print(vardiv)

print()

#Modulus

e1=np.array([1,2.3,4])

varmod=np.mod(e1,2)

print(varmod)

print()

##power

a1=np.array([12,3,4])

varpow=np.power(a1,3)

print(varpow)


[0 4 4 4]

[10 30 21]

[0.5        0.66666667 0.5       ]

[1.  0.3 0. ]

[1728   27   64]


In [36]:
#Modulus

e1=np.array([1,2.3,4])

varmod=np.mod(e1,2)

print(varmod)

[1.  0.3 0. ]


In [48]:
#Airthemetic operations in numpy in 2D array

#addition

import numpy as np

a=np.array([[1,2,3,4],[2,3,4,5]])
b=np.array([[2,5,4,8],[8,4,5,6]])

varadd= np.add(a,b)
print("2D addition")

print()

print(varadd)

print()

## 2D subtraction

c=np.array([[1,2,3,4],[2,3,4,5]])
d=np.array([[2,5,4,8],[8,4,5,6]])

varsub=np.subtract(d,c)

print("2D subtraction")
print()
print(varsub)

print()

##2D Multiplication

c1=np.array([[1,2,3,4],[2,3,4,5]])
d1=np.array([[2,5,4,8],[8,4,5,6]])

varmulti=np.multiply(c1,d1)

print("2D Multiplication")
print()
print(varmulti)

print()

##2D division

c2=np.array([[1,2,3,4],[2,3,4,5]])
d2=np.array([[2,5,4,8],[8,4,5,6]])

vardiv=np.divide(d2,c2)

print("2D division")
print()
print(vardiv)
print()

##2D Modulus

e=np.array([[2,3,4,5],[5,4,6,5]])

varmod=np.mod(e,5)

print("2D Modulus")
print()
print(varmod)
print()



2D addition

[[ 3  7  7 12]
 [10  7  9 11]]

2D subtraction

[[1 3 1 4]
 [6 1 1 1]]

2D Multiplication

[[ 2 10 12 32]
 [16 12 20 30]]

2D division

[[2.         2.5        1.33333333 2.        ]
 [4.         1.33333333 1.25       1.2       ]]

2D Modulus

[[2 3 4 0]
 [0 4 1 0]]

